language: rust
rust:
- stable
- beta
- nightly
GH_TOKEN: 
DEPLOY_TO_GITHUB:
  before_deploy: &1
  - git config --local user.name "Waelwindows"
  - git config --local user.email "waelwindows@hotmail.com"
  - name="farc-$TRAVIS_TAG-$TARGET"
  - mkdir $name
  - cp target/$TARGET/release/examples/farc $name/
  - cp README.md LICENSE $name/
  - tar czvf $name.tar.gz $name
  deploy: &2
    provider: releases
    api_key:
      secure: kmc9Xjy9T0Gvf6k60embsoxUs9ksfMl1UTNp99Ky7hSvoGYM/eFfg2Z1Kq6hBS+uSjAUdEtD0PwUOO1ZyAeMKqOdDnIBKqCvVTjitkRz0T1op0kuQ/s+qQnU+snw5EwKQ5S9UBB+pdGWlh9SBmCjPOAnigohKB8fJsqIgxWt/B6bPCKeahrdA7oMyQ9AAh4NFhnr21QJHRUUQqzpLFl8bKXexZQ45N6DZ7tRTugeMP7OLr8U6H/vXYE6rjM3sW+QkbLPQHh1swIR0naQLxPMyKrH/z1LH5CSSb700wLI6fw4HVTVv6fQgQJFyNypdY/MTNJQL0O4/s+bE+f6KbLjkLVN6AU9MjUyacfn3g9lqufofJJ8QBGm5P3yQhCJlJiZBn8B3bjvBuzxM1CEe3O+sxIktPwD5I9fB0aKEmBspo4L76XrYl8y4ov2YmVrtuaC6dpMJQFNj1n+jgUzOYR3ELrS9Q1fCDvYcMOhVNHiFxsqBt1ik7uWSu7k/AU6yLMdJh0oYOvnFUfRCPfttNjLCD5p9HYTVwZZytszT+jRQ5Bi482RCF9Cnpe3o1SXzgl2ss1RiVYfb/ZF+u34fgHAZUfXaylhUbFij2fdWJrKrZ1yJ7Vr4YALcyfGPwSH58dPe9eFc1PjCbVVLj8WffgEZmtxMFxvNXKckJ8uL9tUQbg=
    file: farc-$TRAVIS_TAG-$TARGET.tar.gz
    skip_cleanup: true
    on:
      all_branches: true
      tags: true
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
  cache: cargo
  include:
  - name: Linux Binary
    env: TARGET=x86_64-unknown-linux-musl
    rust: nightly
    before_script: rustup target add $TARGET
    script: cargo build --release --target $TARGET --example=farc
    addons:
      apt:
        packages:
        - musl-tools
    before_deploy: *1
    deploy: *2
  - name: macOS Binary
    env: MACOSX_DEPLOYMENT_TARGET=10.7 TARGET=x86_64-apple-darwin
    os: osx
    rust: nightly
    script: cargo build --release --target $TARGET --example=farc
    install: true
    before_deploy: *1
    deploy: *2
    #deploy:
    #  provider: releases
    #  api_key:
    #    secure: kmc9Xjy9T0Gvf6k60embsoxUs9ksfMl1UTNp99Ky7hSvoGYM/eFfg2Z1Kq6hBS+uSjAUdEtD0PwUOO1ZyAeMKqOdDnIBKqCvVTjitkRz0T1op0kuQ/s+qQnU+snw5EwKQ5S9UBB+pdGWlh9SBmCjPOAnigohKB8fJsqIgxWt/B6bPCKeahrdA7oMyQ9AAh4NFhnr21QJHRUUQqzpLFl8bKXexZQ45N6DZ7tRTugeMP7OLr8U6H/vXYE6rjM3sW+QkbLPQHh1swIR0naQLxPMyKrH/z1LH5CSSb700wLI6fw4HVTVv6fQgQJFyNypdY/MTNJQL0O4/s+bE+f6KbLjkLVN6AU9MjUyacfn3g9lqufofJJ8QBGm5P3yQhCJlJiZBn8B3bjvBuzxM1CEe3O+sxIktPwD5I9fB0aKEmBspo4L76XrYl8y4ov2YmVrtuaC6dpMJQFNj1n+jgUzOYR3ELrS9Q1fCDvYcMOhVNHiFxsqBt1ik7uWSu7k/AU6yLMdJh0oYOvnFUfRCPfttNjLCD5p9HYTVwZZytszT+jRQ5Bi482RCF9Cnpe3o1SXzgl2ss1RiVYfb/ZF+u34fgHAZUfXaylhUbFij2fdWJrKrZ1yJ7Vr4YALcyfGPwSH58dPe9eFc1PjCbVVLj8WffgEZmtxMFxvNXKckJ8uL9tUQbg=
    #  file: ''
    #  on:
    #    repo: Waelwindows/farc
